name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Debug files
        run: |
          echo "=== ROOT ==="
          dir
          echo "=== package.json ==="
          type package.json

      - name: Install deps
        run: npm install --no-package-lock

      - name: Build EXE
        run: npm run dist:win

      - uses: actions/upload-artifact@v4
        with:
          name: SakuraLauncher-Windows
          path: release/*.exe
